TASK: classification
# this is the config for classification task on sngar-tracking dataset.
# this config is used for the data scaling experiments reported in the paper:
# "Pixels or Positions? Benchmarking Modalities in Group Activity Recognition"
# https://arxiv.org/abs/2511.12606
# GIN backbone + maxpool temporal aggregation + positional edges - data scaling experiment with 35 training matches.
# it has all the hyperparameters value used to reproduce the results reported in the paper.

DATA:
  dataset_name: sngar
  data_modality: tracking_parquet
  data_dir: /home/karkid/opensportslib/tracking-dataset
  preload_data: false
  train:
    type: annotations_train.json
    video_path: ${DATA.data_dir}/train
    path: ${DATA.train.video_path}/train.json
    dataloader:
      batch_size: 32
      shuffle: true
      num_workers: 8
      pin_memory: true
  valid:
    type: annotations_valid.json
    video_path: ${DATA.data_dir}/valid
    path: ${DATA.valid.video_path}/valid.json
    dataloader:
      batch_size: 32
      num_workers: 8
      shuffle: false
  test:
    type: annotations_test.json
    video_path: ${DATA.data_dir}/test
    path: ${DATA.test.video_path}/test.json
    dataloader:
      batch_size: 32
      num_workers: 8
      shuffle: false
  num_frames: 16
  frame_interval: 9
  augmentations:
    vertical_flip: true
    horizontal_flip: true
    team_flip: true
  normalize: true
  num_objects: 23
  feature_dim: 8
  pitch_half_length: 85.0
  pitch_half_width: 50.0
  max_displacement: 110.0
  max_ball_height: 30.0
  data_slicing: # only used for data scaling experiments
    enabled: true
    training_matches: 35

MODEL:
  type: custom
  backbone:
    type: graph_conv
    encoder: gin
    hidden_dim: 64
    num_layers: 20
    dropout: 0.1
  neck:
    type: TemporalAggregation
    agr_type: maxpool
    hidden_dim: 64
    dropout: 0.1
    use_position_encoding: true
  head:
    type: TrackingClassifier
    hidden_dim: 64
    dropout: 0.1
    num_classes: 10
  edge: positional
  k: 8
  r: 15.0

TRAIN:
  monitor: loss # balanced_accuracy, loss
  mode: min # max or min
  enabled: true
  use_weighted_sampler: true
  use_weighted_loss: false
  samples_per_class: 4000
  epochs: 10
  patience: 10
  save_every: 20
  detailed_results: true

  optimizer:
    type: Adam
    lr: 0.001

  scheduler:
    type: ReduceLROnPlateau
    mode: ${TRAIN.mode}
    patience: 10
    factor: 0.1
    min_lr: 1e-8

  criterion:
    type: CrossEntropyLoss

SYSTEM:
 log_dir: ./logs
 save_dir: ./checkpoints_tracking
 use_seed: true
 seed: 42
 GPU: 4
 device: cuda   # auto | cuda | cpu
 gpu_id: 0
