TASK: classification
# this is the config for classification task on sngar-frames dataset.
# this config is used for the main experiments reported in the paper:
# "Pixels or Positions? Benchmarking Modalities in Group Activity Recognition"
# https://arxiv.org/abs/2511.12606
# videomae2 - fully finetuned - data scaling experiment with 40 training matches.

DATA:
  dataset_name: sngar
  data_dir: /home/karkid/opensportslib/sngar-frames
  data_modality: frames_npy
  # max_samples: 100 # only used for quick testing
  num_frames: 16
  frame_size: [224, 224]
  train:
    path: ${DATA.data_dir}/annotations_train.json
    dataloader:
      batch_size: 8 # for frozen backbone, use 64
      # for unfrozen backbone, use 32-16-8 depending on the memory available
      shuffle: true
      num_workers: 8
      pin_memory: true
  valid:
    path: ${DATA.data_dir}/annotations_valid.json
    dataloader:
      batch_size: 8
      num_workers: 8
      shuffle: false
  test:
    path: ${DATA.data_dir}/annotations_test.json
    dataloader:
      batch_size: 8
      num_workers: 8
      shuffle: false
  augmentations:
    random_horizontal_flip: true
    flip_prob: 0.5
    color_jitter: true
    jitter_prob: 0.5
    jitter_params: [0.2, 0.2, 0.2, 0.1]
  data_slicing: # only used for data scaling experiments
    enabled: true
    training_matches: 40

MODEL:
  type: custom
  backbone:
    type: videomae2                  # videomae | videomae2
    pretrained_model: OpenGVLab/VideoMAEv2-Base
    # MCG-NJU/videomae-base | OpenGVLab/VideoMAEv2-Base
    hidden_dim: 768
    freeze: false # true for frozen backbone, false for unfrozen backbone i.e. full-finetuning
    unfreeze_last_n_layers: 0     # 0 = frozen backbone, >0 = unfreeze last N layers
  neck:
    type: TemporalAggregation
    agr_type: maxpool             # avgpool | maxpool | bilstm | tcn | attention
    hidden_dim: 768
    dropout: 0.1
    lstm_dropout: 0.3             # only used when agr_type is bilstm
    num_attention_heads: 8        # only used when agr_type is attention (8 for video, 4 for tracking)
  head:
    type: TrackingClassifier
    hidden_dim: 64
    num_classes: 10               # must match the number of action classes in the dataset
    dropout: 0.1

TRAIN:
  monitor: loss # balanced_accuracy, loss
  mode: min # max or min
  enabled: true
  use_amp: true
  mixup_alpha: 0.2
  use_weighted_sampler: true
  samples_per_class: 4000
  use_weighted_loss: false
  epochs: 100
  patience: 5
  log_interval: 10
  save_every: 5
  detailed_results: true

  criterion:
    type: CrossEntropyLoss

  optimizer:
    type: AdamW
    lr: 0.00005 # tune lr based on the backbone
    betas: [0.9, 0.999]
    eps: 0.0000001
    weight_decay: 0.0001
    amsgrad: false

  scheduler:
    type: ReduceLROnPlateau
    mode: min
    patience: 5
    factor: 0.1
    min_lr: 1e-8

SYSTEM:
  log_dir: ./logs
  save_dir: ./checkpoints_video
  use_seed: true
  seed: 42
  GPU: 1
  device: cuda
  gpu_id: 0
